### ISSUE TITLE
changes to be made

### ISSUE THREAD

**Issue by dharshan-webdev** [revahack/2021#39]
##Changes to be made before saturday

- [x] Reva Hack must be in caps everywhere

- [x] Code for change 👉 code for a change

- [x] Bottom padding is less in medium screens in cover

- [x] Increase Reva's logo to match devfolio

- [x] Schedule 👉 Process Flow

- [x] Change Favicon

- [x] Add faculties in organizers

- [x] Optimize images

- [x] Remove fb and twitter icons from footer

- [x] FAQ left alignment

- [x] Application closing date

- [x] FAQ repeated answer

**Comment by deepvashisth** [comment]
> ##Changes to be made before saturday
> 
> * [x]  Reva Hack must be in caps everywhere
> * [x]  Code for change 👉 code for a change
> * [ ]  Bottom padding is less in medium screens in cover
> * [x]  Increase Reva's logo to match devfolio
> * [x]  Schedule 👉 Process Flow
> * [x]  Change Favicon
> * [ ]  Add faculties in organizers
> * [ ]  Optimize images
> * [x]  Remove fb and twitter icons from footer
> * [x]  FAQ left alignment
> * [x]  Application closing date
> * [x]  FAQ repeated answer

**Comment by shivendrasaurav** [comment]
All Done
